### ISSUE TITLE
Error generating prmtop file

### ISSUE THREAD

**Issue by tovrstra** [MTS-Strathclyde/PC_plus#1]
I'm trying to apply your scripts to the attached pdb file: [example.zip](https://github.com/MTS-Strathclyde/PC_plus/files/1457221/example.zip). I would like to provide my own charges and Lennard-Jones parameters for this molecule, so I run:

```./gen_prmtop.py --input_chg --input_lj ap2mg3.pdb```

Still the script tries to run antechamber on this and generates the following error message:

```
The frozen atom type can only be 1, 2, 3, 7 (aromatic single),
or 8 (aromatic double).
Cannot properly run "/home/toon/local/amber/16/bin/bondtype -f ac -o ANTECHAMBER_AM1BCC.AC -i ANTECHAMBER_AM1BCC_PRE.AC -j full".
/home/toon/local/amber/16/bin/to_be_dispatched/antechamber: Fatal Error!
Cannot properly run "/home/toon/local/amber/16/bin/am1bcc -i ANTECHAMBER_AM1BCC_PRE.AC -o ANTECHAMBER_AM1BCC.AC -f ac -p /home/toon/local/amber/16/dat/antechamber/BCCPARM.DAT -s 2 -j 4".
Traceback (most recent call last):
  File "./gen_prmtop.py", line 487, in <module>
    main(sys.argv[1:])
  File "./gen_prmtop.py", line 462, in main
    prepare_prmtop(args, name)
  File "./gen_prmtop.py", line 402, in prepare_prmtop
    prmtop_name = generate_prmtop(name, args)
  File "./gen_prmtop.py", line 269, in generate_prmtop
    cwd=p)
  File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['antechamber', '-i', 'ap2mg3.pdb', '-fi', 'pdb', '-at', 'gaff', '-o', 'ap2mg3.pdb', '-fo', 'pdb', '-c', 'bcc', '-s', '2', '-nc', '0', '-m', '1']' returned non-zero exit status 1
```

I was hoping that antechamber and am1bcc would not be executed when I provide all non-bonding parameters manually. In principle, these nonbonding parameters are the only ones needed for a 3D-RISM calculation, right? (I'm not sure why `rism3d.snglpnt` takes a complete prmtop file as input.)

**Comment by MaksimMisin** [comment]
This script is definitely out of date and does a lot of strange things. I updated it a bit, importantly removing the redundant charges calculation in case user provides their own charges.

Additionally, everything seems to work much better if you provide mol2 files as an input. So:
```
obabel -ipdb ap2mg3.pdb -omol2 > ap2mg3.mol2
gen_prmtop.py ap2mg3.mol2 -f mol2 --input_chg --input_lj
```
produces valid prmtop.

Regarding why `rism3d.snglpnt` needs prmtop files - I have no idea. 3D-RISM only needs the values of solute-solvent interaction energies in the region of interest. I believe if one could ask around/play a bit with the code, it would be possible to get a modified version of the program that accepts a grid of potential energies as an input and makes all these operations with antechamber unnecessary...

**Comment by tovrstra** [comment]
That worked! Thanks for the quick feedback.
