### ISSUE TITLE
leap error

### ISSUE THREAD

**Issue by kexul** [MTS-Strathclyde/PC_plus#4]
when I check the log, tleap say it can't read some bond type in mol2 file, then I checked the rism3d_pc.py,  I found 
```
ante_out = subprocess.check_output(['antechamber',
                     '-i', '{}.{}'.format(no_p_name, ext),
                     '-fi', ext,
                     '-o', '{}.mol2'.format(no_p_name), # output file
                     '-fo', 'mol2',  # output format describing each residue
                     '-at','amber',  # atom types (gaff2)
                     '-s', '2'       # status info ; 2 means verbose
                     ] + chg,
                     cwd=p)
```
here the atom type were set as 'amber', why it's not 'gaff2' since the tleap use gaff2 force field? And I tried modified it to 'gaff2', the error disappeared but the result seems to be bad.

![image](https://user-images.githubusercontent.com/5920217/88800245-6bce9d80-d1da-11ea-91e1-9e394c4757c2.png)

**Comment by kexul** [comment]
I use amber18, here is the pdb file I've used.

[mobley_3167746_vacuum.zip](https://github.com/MTS-Strathclyde/PC_plus/files/4994832/mobley_3167746_vacuum.zip)

**Comment by MaksimMisin** [comment]
Feel free to use any other force field to generate parameters.

Also, not sure how you are getting an error - here is what I see:
```
$ python rism3d_pc.py mobley_3167746_vacuum.pdb
Starting SFE calculation for mobley_3167746_vacuum.pdb
Running AM1-BCC calculation...
Running 1D-RISM calculation...
Running 3D-RISM calculation...
Calculation has finished
RISM exchem=30.59165778004698 kcal/mol
PC+ dG*(solv)=1.9720613494261485 kcal/mol
Detailed output can be found in mobley_3167746_vacuum_298.15/mobley_3167746_vacuum.log
```

(I used the latest ambertools with all the updates installed).

**Comment by kexul** [comment]
Could you please check your “mobley_3167746_vacuum.log”？The error was there. Or 'leap.log'.

**Comment by MaksimMisin** [comment]
All right - got it. These are all either bond or angle parameters that don't have any impact on the calculation (we are calculating interaction of a static molecule with solvent - for that you don't need to know any force constants, just LJ and electrostatics). Also, I believe leap substitutes the missing parameters with sensible defaults.
